return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  config = function()
    local ts = require("nvim-treesitter")
    ts.setup({
      install_dir = vim.fs.joinpath(vim.fn.stdpath("data"), "site"),
    })

    if vim.fn.executable("tree-sitter") == 1 then
      ts.install({
        "awk",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cpp",
        "css",
        "csv",
        "diff",
        "elixir",
        "elm",
        "erlang",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "http",
        "ini",
        "java",
        "javadoc",
        "javascript",
        "jq",
        "json",
        "kdl",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "nginx",
        "nix",
        "perl",
        "php",
        "phpdoc",
        "powershell",
        "prisma",
        "pug",
        "python",
        "robot",
        "rst",
        "ruby",
        "rust",
        "scss",
        "sql",
        "styled",
        "swift",
        "tmux",
        "toml",
        "tsv",
        "tsx",
        "twig",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
      }, {
        force = false,
        generate = false,
        max_jobs = 4,
        summary = false,
      })
    end
  end,
}
