[terminal]
shell = { program = "C:\\WINDOWS\\system32\\wsl.exe", args = [
  "--distribution",
  "Ubuntu",
  "--cd",
  "~",
] }

[[hints.enabled]]
regex = "(https?://[^\\s]+)"
command = { program = "cmd", args = ["/c", "start", ""] }
mouse = { enabled = true, mods = "Shift" }
hyperlinks = true
post_processing = true
